// Code generated by go-swagger; DO NOT EDIT.

package buckets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
)

// StorageBucketRemoveHTTPReader is a Reader for the StorageBucketRemoveHTTP structure.
type StorageBucketRemoveHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageBucketRemoveHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageBucketRemoveHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageBucketRemoveHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /resource/v3/storage/{id}/s3/bucket/{name}] storageBucketRemoveHttp", response, response.Code())
	}
}

// NewStorageBucketRemoveHTTPNoContent creates a StorageBucketRemoveHTTPNoContent with default headers values
func NewStorageBucketRemoveHTTPNoContent() *StorageBucketRemoveHTTPNoContent {
	return &StorageBucketRemoveHTTPNoContent{}
}

/*
StorageBucketRemoveHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageBucketRemoveHTTPNoContent struct {
}

// IsSuccess returns true when this storage bucket remove Http no content response has a 2xx status code
func (o *StorageBucketRemoveHTTPNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this storage bucket remove Http no content response has a 3xx status code
func (o *StorageBucketRemoveHTTPNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage bucket remove Http no content response has a 4xx status code
func (o *StorageBucketRemoveHTTPNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this storage bucket remove Http no content response has a 5xx status code
func (o *StorageBucketRemoveHTTPNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this storage bucket remove Http no content response a status code equal to that given
func (o *StorageBucketRemoveHTTPNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the storage bucket remove Http no content response
func (o *StorageBucketRemoveHTTPNoContent) Code() int {
	return 204
}

func (o *StorageBucketRemoveHTTPNoContent) Error() string {
	return fmt.Sprintf("[DELETE /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpNoContent ", 204)
}

func (o *StorageBucketRemoveHTTPNoContent) String() string {
	return fmt.Sprintf("[DELETE /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpNoContent ", 204)
}

func (o *StorageBucketRemoveHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageBucketRemoveHTTPBadRequest creates a StorageBucketRemoveHTTPBadRequest with default headers values
func NewStorageBucketRemoveHTTPBadRequest() *StorageBucketRemoveHTTPBadRequest {
	return &StorageBucketRemoveHTTPBadRequest{}
}

/*
StorageBucketRemoveHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageBucketRemoveHTTPBadRequest struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this storage bucket remove Http bad request response has a 2xx status code
func (o *StorageBucketRemoveHTTPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this storage bucket remove Http bad request response has a 3xx status code
func (o *StorageBucketRemoveHTTPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage bucket remove Http bad request response has a 4xx status code
func (o *StorageBucketRemoveHTTPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this storage bucket remove Http bad request response has a 5xx status code
func (o *StorageBucketRemoveHTTPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this storage bucket remove Http bad request response a status code equal to that given
func (o *StorageBucketRemoveHTTPBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the storage bucket remove Http bad request response
func (o *StorageBucketRemoveHTTPBadRequest) Code() int {
	return 400
}

func (o *StorageBucketRemoveHTTPBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageBucketRemoveHTTPBadRequest) String() string {
	return fmt.Sprintf("[DELETE /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketRemoveHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageBucketRemoveHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketRemoveHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
