// Code generated by go-swagger; DO NOT EDIT.

package buckets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
)

// StorageBucketCreateHTTPReader is a Reader for the StorageBucketCreateHTTP structure.
type StorageBucketCreateHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageBucketCreateHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageBucketCreateHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageBucketCreateHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewStorageBucketCreateHTTPConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /resource/v3/storage/{id}/s3/bucket/{name}] storageBucketCreateHttp", response, response.Code())
	}
}

// NewStorageBucketCreateHTTPNoContent creates a StorageBucketCreateHTTPNoContent with default headers values
func NewStorageBucketCreateHTTPNoContent() *StorageBucketCreateHTTPNoContent {
	return &StorageBucketCreateHTTPNoContent{}
}

/*
StorageBucketCreateHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageBucketCreateHTTPNoContent struct {
}

// IsSuccess returns true when this storage bucket create Http no content response has a 2xx status code
func (o *StorageBucketCreateHTTPNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this storage bucket create Http no content response has a 3xx status code
func (o *StorageBucketCreateHTTPNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage bucket create Http no content response has a 4xx status code
func (o *StorageBucketCreateHTTPNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this storage bucket create Http no content response has a 5xx status code
func (o *StorageBucketCreateHTTPNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this storage bucket create Http no content response a status code equal to that given
func (o *StorageBucketCreateHTTPNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the storage bucket create Http no content response
func (o *StorageBucketCreateHTTPNoContent) Code() int {
	return 204
}

func (o *StorageBucketCreateHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpNoContent ", 204)
}

func (o *StorageBucketCreateHTTPNoContent) String() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpNoContent ", 204)
}

func (o *StorageBucketCreateHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageBucketCreateHTTPBadRequest creates a StorageBucketCreateHTTPBadRequest with default headers values
func NewStorageBucketCreateHTTPBadRequest() *StorageBucketCreateHTTPBadRequest {
	return &StorageBucketCreateHTTPBadRequest{}
}

/*
StorageBucketCreateHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageBucketCreateHTTPBadRequest struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this storage bucket create Http bad request response has a 2xx status code
func (o *StorageBucketCreateHTTPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this storage bucket create Http bad request response has a 3xx status code
func (o *StorageBucketCreateHTTPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage bucket create Http bad request response has a 4xx status code
func (o *StorageBucketCreateHTTPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this storage bucket create Http bad request response has a 5xx status code
func (o *StorageBucketCreateHTTPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this storage bucket create Http bad request response a status code equal to that given
func (o *StorageBucketCreateHTTPBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the storage bucket create Http bad request response
func (o *StorageBucketCreateHTTPBadRequest) Code() int {
	return 400
}

func (o *StorageBucketCreateHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageBucketCreateHTTPBadRequest) String() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageBucketCreateHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketCreateHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageBucketCreateHTTPConflict creates a StorageBucketCreateHTTPConflict with default headers values
func NewStorageBucketCreateHTTPConflict() *StorageBucketCreateHTTPConflict {
	return &StorageBucketCreateHTTPConflict{}
}

/*
StorageBucketCreateHTTPConflict describes a response with status code 409, with default header values.

ErrResponse
*/
type StorageBucketCreateHTTPConflict struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this storage bucket create Http conflict response has a 2xx status code
func (o *StorageBucketCreateHTTPConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this storage bucket create Http conflict response has a 3xx status code
func (o *StorageBucketCreateHTTPConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage bucket create Http conflict response has a 4xx status code
func (o *StorageBucketCreateHTTPConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this storage bucket create Http conflict response has a 5xx status code
func (o *StorageBucketCreateHTTPConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this storage bucket create Http conflict response a status code equal to that given
func (o *StorageBucketCreateHTTPConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the storage bucket create Http conflict response
func (o *StorageBucketCreateHTTPConflict) Code() int {
	return 409
}

func (o *StorageBucketCreateHTTPConflict) Error() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpConflict  %+v", 409, o.Payload)
}

func (o *StorageBucketCreateHTTPConflict) String() string {
	return fmt.Sprintf("[POST /resource/v3/storage/{id}/s3/bucket/{name}][%d] storageBucketCreateHttpConflict  %+v", 409, o.Payload)
}

func (o *StorageBucketCreateHTTPConflict) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageBucketCreateHTTPConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
