// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventResponse Event for storage notification
//
// swagger:model EventResponse
type EventResponse struct {

	// Bucket name
	BucketName string `json:"bucket_name,omitempty"`

	// Number of bytes. When you reach this number, you will receive an email notification.
	// Example: 500
	Bytes uint64 `json:"bytes,omitempty"`

	// Count as limit
	// Example: 5
	Count uint64 `json:"count,omitempty"`

	// name of type notification
	// Example: reaching_used_space, reaching_files_quantity, reaching_used_traffic, reaching_used_requests
	// Required: true
	Name *string `json:"name"`

	// Storage name
	StorageName string `json:"storage_name,omitempty"`

	// Bucket ID
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this event response
func (m *EventResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventResponse) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this event response based on context it is used
func (m *EventResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventResponse) UnmarshalBinary(b []byte) error {
	var res EventResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
