// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LimitByCount LimitByCount input
//
// swagger:model LimitByCount
type LimitByCount struct {

	// Bucket name
	BucketName string `json:"bucket_name,omitempty"`

	// Limit count value. When you reach this limit, you will receive an email notification
	Count uint64 `json:"count,omitempty"`

	// Storage name
	StorageName string `json:"storage_name,omitempty"`

	// Bucket ID
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this limit by count
func (m *LimitByCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this limit by count based on context it is used
func (m *LimitByCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LimitByCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LimitByCount) UnmarshalBinary(b []byte) error {
	var res LimitByCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
