// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RedefinedVar RedefinedVar entity
//
// swagger:model RedefinedVar
type RedefinedVar struct {

	// for
	For interface{} `json:"for,omitempty"`

	// ID
	ID int64 `json:"id,omitempty"`

	// replace to
	ReplaceTo string `json:"replace_to,omitempty"`

	// resource
	Resource string `json:"resource,omitempty"`
}

// Validate validates this redefined var
func (m *RedefinedVar) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this redefined var based on context it is used
func (m *RedefinedVar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RedefinedVar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RedefinedVar) UnmarshalBinary(b []byte) error {
	var res RedefinedVar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
