// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StatsMetrics stats metrics
//
// swagger:model StatsMetrics
type StatsMetrics struct {

	// Maximum number of files within the specified time period
	FileQuantitySumMax uint64 `json:"file_quantity_sum_max,omitempty"`

	// Total number of incoming requests within the specified time period
	RequestsInSum uint64 `json:"requests_in_sum,omitempty"`

	// Total number of requests from the edges within the specified time period
	RequestsOutEdgesSum uint64 `json:"requests_out_edges_sum,omitempty"`

	// Total number of outсoming requests without requests from the edges within the specified time period
	RequestsOutWoEdgesSum uint64 `json:"requests_out_wo_edges_sum,omitempty"`

	// Total number of requests within the specified time period
	RequestsSum uint64 `json:"requests_sum,omitempty"`

	// RequestsWoEdgesSum is sum of requests without edges out requests for grouped period
	RequestsWoEdgesSum uint64 `json:"requests_wo_edges_sum,omitempty"`

	// Maximum amount of all file sizes within the specified time period
	SizeSumMax uint64 `json:"size_sum_max,omitempty"`

	// Mean amount of all file sizes within the specified time period
	SizeSumMean uint64 `json:"size_sum_mean,omitempty"`

	// Total amount of incoming traffic within the specified time period
	TrafficInSum uint64 `json:"traffic_in_sum,omitempty"`

	// Total number of traffic from the edges within the specified time period
	TrafficOutEdgesSum uint64 `json:"traffic_out_edges_sum,omitempty"`

	// Total number of outсoming traffic without requests from the edges within the specified time period
	TrafficOutWoEdgesSum uint64 `json:"traffic_out_wo_edges_sum,omitempty"`

	// Total amount of traffic within the specified time period
	TrafficSum uint64 `json:"traffic_sum,omitempty"`
}

// Validate validates this stats metrics
func (m *StatsMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stats metrics based on context it is used
func (m *StatsMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatsMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatsMetrics) UnmarshalBinary(b []byte) error {
	var res StatsMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
