// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
)

// KeyUnlinkHTTPReader is a Reader for the KeyUnlinkHTTP structure.
type KeyUnlinkHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KeyUnlinkHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewKeyUnlinkHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKeyUnlinkHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewKeyUnlinkHTTPNoContent creates a KeyUnlinkHTTPNoContent with default headers values
func NewKeyUnlinkHTTPNoContent() *KeyUnlinkHTTPNoContent {
	return &KeyUnlinkHTTPNoContent{}
}

/*
KeyUnlinkHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type KeyUnlinkHTTPNoContent struct {
}

// IsSuccess returns true when this key unlink Http no content response has a 2xx status code
func (o *KeyUnlinkHTTPNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this key unlink Http no content response has a 3xx status code
func (o *KeyUnlinkHTTPNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this key unlink Http no content response has a 4xx status code
func (o *KeyUnlinkHTTPNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this key unlink Http no content response has a 5xx status code
func (o *KeyUnlinkHTTPNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this key unlink Http no content response a status code equal to that given
func (o *KeyUnlinkHTTPNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *KeyUnlinkHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/unlink][%d] keyUnlinkHttpNoContent ", 204)
}

func (o *KeyUnlinkHTTPNoContent) String() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/unlink][%d] keyUnlinkHttpNoContent ", 204)
}

func (o *KeyUnlinkHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewKeyUnlinkHTTPBadRequest creates a KeyUnlinkHTTPBadRequest with default headers values
func NewKeyUnlinkHTTPBadRequest() *KeyUnlinkHTTPBadRequest {
	return &KeyUnlinkHTTPBadRequest{}
}

/*
KeyUnlinkHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type KeyUnlinkHTTPBadRequest struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this key unlink Http bad request response has a 2xx status code
func (o *KeyUnlinkHTTPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this key unlink Http bad request response has a 3xx status code
func (o *KeyUnlinkHTTPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this key unlink Http bad request response has a 4xx status code
func (o *KeyUnlinkHTTPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this key unlink Http bad request response has a 5xx status code
func (o *KeyUnlinkHTTPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this key unlink Http bad request response a status code equal to that given
func (o *KeyUnlinkHTTPBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *KeyUnlinkHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/unlink][%d] keyUnlinkHttpBadRequest  %+v", 400, o.Payload)
}

func (o *KeyUnlinkHTTPBadRequest) String() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/key/{key_id}/unlink][%d] keyUnlinkHttpBadRequest  %+v", 400, o.Payload)
}

func (o *KeyUnlinkHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *KeyUnlinkHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
