// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
)

// StorageRestoreHTTPReader is a Reader for the StorageRestoreHTTP structure.
type StorageRestoreHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageRestoreHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewStorageRestoreHTTPNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageRestoreHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageRestoreHTTPNoContent creates a StorageRestoreHTTPNoContent with default headers values
func NewStorageRestoreHTTPNoContent() *StorageRestoreHTTPNoContent {
	return &StorageRestoreHTTPNoContent{}
}

/*
StorageRestoreHTTPNoContent describes a response with status code 204, with default header values.

A SuccessResponse is a response that shows that operations was completed successfully
*/
type StorageRestoreHTTPNoContent struct {
}

// IsSuccess returns true when this storage restore Http no content response has a 2xx status code
func (o *StorageRestoreHTTPNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this storage restore Http no content response has a 3xx status code
func (o *StorageRestoreHTTPNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage restore Http no content response has a 4xx status code
func (o *StorageRestoreHTTPNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this storage restore Http no content response has a 5xx status code
func (o *StorageRestoreHTTPNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this storage restore Http no content response a status code equal to that given
func (o *StorageRestoreHTTPNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *StorageRestoreHTTPNoContent) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/restore][%d] storageRestoreHttpNoContent ", 204)
}

func (o *StorageRestoreHTTPNoContent) String() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/restore][%d] storageRestoreHttpNoContent ", 204)
}

func (o *StorageRestoreHTTPNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStorageRestoreHTTPBadRequest creates a StorageRestoreHTTPBadRequest with default headers values
func NewStorageRestoreHTTPBadRequest() *StorageRestoreHTTPBadRequest {
	return &StorageRestoreHTTPBadRequest{}
}

/*
StorageRestoreHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageRestoreHTTPBadRequest struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this storage restore Http bad request response has a 2xx status code
func (o *StorageRestoreHTTPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this storage restore Http bad request response has a 3xx status code
func (o *StorageRestoreHTTPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage restore Http bad request response has a 4xx status code
func (o *StorageRestoreHTTPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this storage restore Http bad request response has a 5xx status code
func (o *StorageRestoreHTTPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this storage restore Http bad request response a status code equal to that given
func (o *StorageRestoreHTTPBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *StorageRestoreHTTPBadRequest) Error() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/restore][%d] storageRestoreHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageRestoreHTTPBadRequest) String() string {
	return fmt.Sprintf("[POST /provisioning/v1/storage/{id}/restore][%d] storageRestoreHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageRestoreHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageRestoreHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
