// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
)

// StorageListBucketsHTTPReader is a Reader for the StorageListBucketsHTTP structure.
type StorageListBucketsHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageListBucketsHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStorageListBucketsHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStorageListBucketsHTTPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStorageListBucketsHTTPOK creates a StorageListBucketsHTTPOK with default headers values
func NewStorageListBucketsHTTPOK() *StorageListBucketsHTTPOK {
	return &StorageListBucketsHTTPOK{}
}

/*
StorageListBucketsHTTPOK describes a response with status code 200, with default header values.

StorageListBucketsEndpointRes
*/
type StorageListBucketsHTTPOK struct {
	Payload *models.StorageListBucketsEndpointRes
}

// IsSuccess returns true when this storage list buckets Http o k response has a 2xx status code
func (o *StorageListBucketsHTTPOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this storage list buckets Http o k response has a 3xx status code
func (o *StorageListBucketsHTTPOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage list buckets Http o k response has a 4xx status code
func (o *StorageListBucketsHTTPOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this storage list buckets Http o k response has a 5xx status code
func (o *StorageListBucketsHTTPOK) IsServerError() bool {
	return false
}

// IsCode returns true when this storage list buckets Http o k response a status code equal to that given
func (o *StorageListBucketsHTTPOK) IsCode(code int) bool {
	return code == 200
}

func (o *StorageListBucketsHTTPOK) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpOK  %+v", 200, o.Payload)
}

func (o *StorageListBucketsHTTPOK) String() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpOK  %+v", 200, o.Payload)
}

func (o *StorageListBucketsHTTPOK) GetPayload() *models.StorageListBucketsEndpointRes {
	return o.Payload
}

func (o *StorageListBucketsHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StorageListBucketsEndpointRes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageListBucketsHTTPBadRequest creates a StorageListBucketsHTTPBadRequest with default headers values
func NewStorageListBucketsHTTPBadRequest() *StorageListBucketsHTTPBadRequest {
	return &StorageListBucketsHTTPBadRequest{}
}

/*
StorageListBucketsHTTPBadRequest describes a response with status code 400, with default header values.

ErrResponse
*/
type StorageListBucketsHTTPBadRequest struct {
	Payload *models.ErrResponse
}

// IsSuccess returns true when this storage list buckets Http bad request response has a 2xx status code
func (o *StorageListBucketsHTTPBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this storage list buckets Http bad request response has a 3xx status code
func (o *StorageListBucketsHTTPBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this storage list buckets Http bad request response has a 4xx status code
func (o *StorageListBucketsHTTPBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this storage list buckets Http bad request response has a 5xx status code
func (o *StorageListBucketsHTTPBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this storage list buckets Http bad request response a status code equal to that given
func (o *StorageListBucketsHTTPBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *StorageListBucketsHTTPBadRequest) Error() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageListBucketsHTTPBadRequest) String() string {
	return fmt.Sprintf("[GET /provisioning/v1/storage/{id}/s3/buckets][%d] storageListBucketsHttpBadRequest  %+v", 400, o.Payload)
}

func (o *StorageListBucketsHTTPBadRequest) GetPayload() *models.ErrResponse {
	return o.Payload
}

func (o *StorageListBucketsHTTPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
